FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.26.7-1788245275@sha256:8cf89835994846ca0dffb9078e3a5638c57ec6175750f0af02fbe9c9942696d3 AS go-builder
ARG TARGETOS=linux
ARG TARGETARCH=amd64
WORKDIR /build
COPY backend/ .
USER root
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -buildvcs=false -trimpath -o /fakegithub ./cmd/fakegithub

FROM registry.access.redhat.com/ubi9/ubi:1788245146@sha256:ae8730de9161f4e98dbe22fef5eba494b0bfe5886be8dc3c4ff687c2e954daf6 AS act-downloader
ARG TARGETARCH=amd64
ARG ACT_VERSION=v0.2.89
ARG ACT_SHA256_amd64=0191d6f1f3b716b5c55820032605d05fc3c1cdbf581ebeff655019e5dd1524c0
ARG ACT_SHA256_arm64=daa8679ba9615a74d2d0cec321dc593f21948a2a11bb65862b063d8b930f4bcb
RUN ARCH=$([ "$TARGETARCH" = "amd64" ] && echo "x86_64" || echo "arm64") \
  && eval "CHECKSUM=\${ACT_SHA256_${TARGETARCH}}" \
  && curl -fsSL \
  "https://github.com/nektos/act/releases/download/${ACT_VERSION}/act_Linux_${ARCH}.tar.gz" \
  -o /tmp/act.tar.gz \
  && echo "${CHECKSUM}  /tmp/act.tar.gz" | sha256sum -c - \
  && tar -xz -C /tmp -f /tmp/act.tar.gz act \
  && chmod +x /tmp/act


FROM registry.access.redhat.com/ubi9/ubi:1788245146@sha256:ae8730de9161f4e98dbe22fef5eba494b0bfe5886be8dc3c4ff687c2e954daf6

RUN dnf install -y git nodejs podman buildah fuse-overlayfs && \
  dnf clean all

COPY --from=go-builder     /fakegithub               /usr/local/bin/fakegithub
COPY --from=act-downloader /tmp/act                  /usr/local/bin/act
COPY hack/fakegithub-entrypoint.sh                   /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
